export interface User {
    id: number,
    firstName: string,
    lastName: string,
    email: string,
    password: string,
    cellphone: string,
    gender: string,
    birthDate: string,
    rfID: string,
    bmi: string,
    bmiNumber: string,
    weight: string,
    height: string,
    prisMember: string,
    membershipDateStart: string,
    membershipDateEnd: string,
    createdAt: string,
    updatedAt: string,
}