export interface User {
    id?: number,
    firstName: string,
    lastName: string,
    middleName: string,
    suffix: string,
    email: string,
    password?: string,
    cellphone: string,
    sex: string,
    birthDate: string | Date,
    rfID: string,
    bmi: string,
    bmiNumber: string,
    weight: string,
    height: string,
    isMember?: string,
    membershipDateStart?: string,
    membershipDateEnd?: string,
    createdAt?: string,
    updatedAt?: string,
    role: string
}